### ISSUE TITLE
Update to the new API

### ISSUE THREAD

**Issue by ThomasRocha82** [tyjen/Plaid.Net#1]
Hi,

It seems that Plaid has labeled the tartan environment as "legacy" (https://tartan.plaid.com). Which I see this environment being used in your test cases.

Is this library compatible with their latest API version? if not, are there any plans to update?

https://plaid.com/docs/legacy/api/ - Legacy Documentation
https://plaid.com/docs/api/ - Current version Documentation

Respectfully,
Christopher Kaelin

**Comment by tyjen** [comment]
Hi Chris --

This library only supports the legacy version of Plaid. I have plans to jump to the latest api version within the next couple of months, however it's not a very high priority in my company right now.
